server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management_chz?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 18325105894
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8


pagehelper:
  helper-dialect: mysql
